linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true

  staticcheck:
    checks: ['all', '-ST1005', '-ST1000', '-SA4000', '-SA9004', '-SA1019', '-SA1008', '-U1000', '-ST1016']

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - durationcheck
    - gocritic
    - gofumpt
    - gomodguard
    - goconst
    - lll
    - mnd
    - revive
    - tenv
    - typecheck
    - unconvert
    - unused
