services:
  app:
    image: unluckyyy/go-telegram-oidc:0.1.1
    environment:
      TG_TOKEN: $TG_TOKEN
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      REDIRECT_HOST: http://10.0.0.100:8080/
      AUTH_URL: http://10.0.0.100:8180/auth/realms/tg/protocol/openid-connect/auth
      TOKEN_URL: http://10.0.0.100:8180/auth/realms/tg/protocol/openid-connect/token
    ports:
      - '8080:8080'

  postgres:
    image: postgres:16.4-alpine
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: keycloak
    expose:
      - 5432

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1234
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: 1234
      KC_HTTP_RELATIVE_PATH: '/auth'
    command:
      - 'start-dev'
      - '--import-realm'
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json:ro
    expose:
      - 8080
    ports:
      - '8180:8080'

volumes:
  postgres-keycloak-data:
